analytics: {}
color:
  brandColors:
    - '#000000'
    - '#ffffb5'
    - '#3586b4'
    - '#52eaff'
    - '#ff6540'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 1
  saturation: 0.912522436119616
cta: {}
layout_spectrum: 0
name: frenzymetal
opengraph: {}
purpose: []
typography_spectrum: 0.07453
