name: frenzymetal
favicon: null
layout_spectrum: 0.31275
typography_spectrum: 0.07453
title: Frenzy Metal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffb5'
    - '#3586b4'
    - '#52eaff'
    - '#ff6540'
  brandStrength: 0.125
  lightness: 0.8117506096605211
  saturation: 0.912522436119616
  rhythmicContrast: 0.7291738910134882
purpose: []
