name: frenzymetal
favicon: null
layout_spectrum: 0.31274883169680834
typography_spectrum: 0.07453
title: Frenzy Metal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f4ff00'
    - '#030303'
    - '#363636'
    - '#b6b6b6'
  brandStrength: 0.1478650406934321
  lightness: 0.8117506096605211
  saturation: 0.912522436119616
  rhythmicContrast: 0.7291738910134882
purpose: []
